package main

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func main() {
	fmt.Println("fake-goose: starting")
	fmt.Printf("fake-goose: args=%s\n", strings.Join(os.Args[1:], " "))
	fmt.Printf("fake-goose: cwd=%s\n", mustGetwd())

	// Parse workspace_dir from --params flags.
	workDir := "."
	for i, arg := range os.Args {
		if arg == "--params" && i+1 < len(os.Args) {
			val := os.Args[i+1]
			if strings.HasPrefix(val, "workspace_dir=") {
				workDir = strings.TrimPrefix(val, "workspace_dir=")
			}
		}
	}

	// Simulate progress output.
	phases := []string{
		"Phase 1: Discovery",
		"Phase 2: Fix Loop - Round 1",
		"Phase 3: Final Validation",
		"Phase 4: Report Generation",
	}
	for _, phase := range phases {
		fmt.Printf("fake-goose: %s\n", phase)
		time.Sleep(500 * time.Millisecond)
	}

	// Write a dummy report.
	reportPath := workDir + "/report.html"
	report := `<!DOCTYPE html>
<html>
<head><title>Migration Report</title></head>
<body>
<h1>Migration Report (fake)</h1>
<p>Source: PatternFly 5</p>
<p>Target: PatternFly 6</p>
<p>Status: Complete</p>
<p>Generated by fake-goose at ` + time.Now().Format(time.RFC3339) + `</p>
</body>
</html>`
	err := os.WriteFile(reportPath, []byte(report), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fake-goose: error writing report: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("fake-goose: wrote report to %s\n", reportPath)
	fmt.Println("fake-goose: done")
}

func mustGetwd() string {
	d, err := os.Getwd()
	if err != nil {
		return "<error>"
	}
	return d
}
